import { mount } from "svelte";
import "./app.css";
import App from "./App.svelte";
import { DEMO, installDemo } from "./lib/demobackend.js";

installDemo();                                          // the GitHub Pages demo (#2669): the API from static files
import bangers from "@fontsource/bangers/files/bangers-latin-400-normal.woff2?url";

// Bangers (SIL OFL 1.1, bundled — the Pi may have no internet): the comic splash lettering (#2434).
if (globalThis.FontFace) {
  const face = new FontFace("Bangers", `url(${bangers}) format("woff2")`, { display: "swap" });
  document.fonts.add(face);
  face.load().catch(() => {});                          // ready before the first combo
}

if ("serviceWorker" in navigator && !DEMO) {
  if (import.meta.env.DEV) {
    // Dev server: no service worker — it would serve stale modules and defeat hot reload.
    navigator.serviceWorker.getRegistrations().then(rs => rs.forEach(r => r.unregister()));
  } else {
    // sw.js is Workbox's, generated by the build (vite-plugin-pwa) with this build's precache: a new
    // build's worker takes over, and the page reloads once so it runs the new files — never a stale app.
    const hadController = !!navigator.serviceWorker.controller;
    navigator.serviceWorker.addEventListener("controllerchange", () => { if (hadController) location.reload(); });
    navigator.serviceWorker.register("/sw.js").catch(() => {});
  }
}

mount(App, { target: document.getElementById("app") });
